### ISSUE TITLE
Using makeStructuredView() with arrays?

### ISSUE THREAD

**Issue by edelmanjm** [greggman/webgpu-utils#3]
Hi! Fairly new to WebGPU, so I'm not sure if this is a limitation of this library/WebGPU or if I'm just doing things wrong.

I have a shader with the following simple storage buffer:
```
@group(0) @binding(2)
var<storage> test: array<u32>;
```

I'm trying to use `makeShaderDataDefinitions()` and `makeStructuredView()` to assist with populating the buffer. I call the following:

```
const defs = makeShaderDataDefinitions(myShader);
makeStructuredView(defs.storages.test).set([10, 20]);
```

This, however, results in the following error on [`buffer-views.ts:128`](https://github.com/greggman/webgpu-utils/blob/c2588c6407a3f5d80abce3f4dd494209dbf53be5/src/buffer-views.ts#L158):

```
RangeError: Invalid typed array length: 1
    at new Uint32Array (<anonymous>)
    at eval (eval at makeIntrinsicTypedArrayView (http://localhost:1234/bundle.js:4001:9), <anonymous>:1:1)
    at makeIntrinsicTypedArrayView (http://localhost:1234/bundle.js:4001:9)
    at makeViews (http://localhost:1234/bundle.js:4032:24)
    at makeTypedArrayViews (http://localhost:1234/bundle.js:4056:21)
    at makeStructuredView (http://localhost:1234/bundle.js:4116:19)
    at Renderer.initializeAPI (http://localhost:1234/bundle.js:1140:77)
    at async App.run (http://localhost:1234/bundle.js:967:9)
```

This issue doesn't occur if the storage buffer is defined as a single element instead of an array:
```
@group(0) @binding(2)
var<storage> test: u32;
```
```
const defs = makeShaderDataDefinitions(myShader);
makeStructuredView(defs.storages.test).set(10);
```

Similarly, populating a less-trivially defined buffer also fails if the buffer is of type `array<my_struct>`, but succeeds of the type is of `my_struct`:

```
struct my_struct {
    ty: u32,
    ...
}

@group(0) @binding(1)
var<storage> my_structs: array<my_struct>;
```

```
TypeError: Cannot read properties of undefined (reading 'ty')
    at eval (eval at setStructuredView (http://localhost:1234/bundle.js:4138:33), <anonymous>:1:8)
    at setStructuredView (http://localhost:1234/bundle.js:4138:33)
    at http://localhost:1234/bundle.js:4132:13
    at Array.forEach (<anonymous>)
    at setStructuredView (http://localhost:1234/bundle.js:4131:14)
    at Object.set (http://localhost:1234/bundle.js:4160:13)
    at Renderer.initializeAPI (http://localhost:1234/bundle.js:1181:23)
    at async App.run (http://localhost:1234/bundle.js:967:9)
```

Am I missing something? Do I need to be specifying a size somewhere? Or is this just not possible?

**Comment by greggman** [comment]
Sorry, I checked and you could use `setStructuredValues` but you could not use `makeStructuredView`.

Fixed in 0.13.0

Also, I need to write more docs. `makeStructuredView` doesn't know the size of an unsized array which is what 

```
@group(0) @binding(2)
var<storage> test: array<u32>;
```

is

So, in that case, you need to give in an arrayBuffer 

```
const defs = makeShaderDataDefinitions(wgsl);
const stv = makeStructuredViews(defs.storages.test, new ArrayBuffer(20))
stv.set([1, 2, 3, 4, 5);
```

**Comment by edelmanjm** [comment]
Gotcha, thanks. So a fixed sized array should work fine using both `makeShaderDataDefinitions()` and `makeStructuredView()`? It seems to be behaving in my tests.

**Comment by greggman** [comment]
In 0.13.0 an unsized array should work with `makeStructuredView`. You just have to pass in an `ArrayBuffer` since otherwise it doesn't know how big to make the array

**Comment by edelmanjm** [comment]
Hmm, that doesn't seem to be working for me.
```
@group(0) @binding(2)
var<storage> test: array<u32>;
```

```
const stv = makeStructuredView(defs.storages.test, new ArrayBuffer(20))
stv.set([1, 2, 3, 4, 5]);
```
gives me
```
webgpu-utils.module.js:231 Uncaught (in promise) RangeError: offset is out of bounds
    at Uint32Array.set (<anonymous>)
    at setStructuredView (webgpu-utils.module.js:231:1)
    at Object.set (webgpu-utils.module.js:266:1)
    at Renderer.initializeAPI (renderer.ts:96:9)
    at async App.run (main.ts:31:5)
```

Making the byte length longer than required also doesn't seem to work.

**Comment by greggman** [comment]
Are you using 0.13.0?

It's working here

https://jsfiddle.net/greggman/08enampL/

**Comment by edelmanjm** [comment]
Ah my bad, forgot to run `npm install`. Working now!
